### ISSUE TITLE
redis auth fail

### ISSUE THREAD

**Issue by chowyu08** [emqtt/emq-auth-redis#20]
I run emqtt v2.0.6 in docker on os of ubuntu 14.04 , an start a redis on os,
but enable Plugins "emq_auth_redis" on the dashbord.
 when I start an client to connect emqtt ,auth failed.
redis data :
![image](https://cloud.githubusercontent.com/assets/16483518/21758837/894c6c16-d67a-11e6-8e84-0dbebfebbc45.png)

redis monitor:
![image](https://cloud.githubusercontent.com/assets/16483518/21758847/9956d75e-d67a-11e6-80ec-41a205d23fc1.png)

emqtt console:
![image](https://cloud.githubusercontent.com/assets/16483518/21758868/afe0ea78-d67a-11e6-8e65-630aab8700d9.png)

**Comment by huangdan** [comment]
hi, please configure the 'etc/plugins/emq_auth_redis.conf' if you use the plain password:

```
auth.redis.password_hash = plain
```

**Comment by vowstar** [comment]
@emqplus @huangdan Could you set ``auth.redis.password_hash = plain`` rather than sha256 by default? I think the hash calculate load should not on emq server. And many new user don't notice the sha256 feature by default.

**Comment by emqplus** [comment]
@vowstar   `auth.redis.password_hash = plain` by default in 2.1.0-beta.2 release.
