### ISSUE TITLE
Auth failure in version 2.1.2 with plain password hash

### ISSUE THREAD

**Issue by totojack** [emqtt/emq-auth-redis#36]
**Environment**

OS: Alpine 3.5 (docker)
Erlang/OTP:
EMQ: 2.1.2
Redis: 3.2 (Alpine docker)

**Problem**

It seems authentication is failing using plain password hash. I'm trying with custom user "user0" "pass0". This is the log emqtt returns on console after auth failure:

```
16:19:27.447 [info] Client(undefined@172.22.0.1:42696): RECV CONNECT(Q0, R0, D0, ClientId=MQTT_FX_Client, ProtoName=MQIsdp, ProtoVsn=3, CleanSess=true, KeepAlive=60, Username=user0, Password=******)
16:19:27.449 [error] Client(MQTT_FX_Client@172.22.0.1:42696): Username 'user0' login failed for {{case_clause,{ok,<<"pass0">>}},[{emq_auth_redis,check,3,[{file,"src/emq_auth_redis.erl"},{line,41}]},{emqttd_access_control,auth,3,[{file,"src/emqttd_access_control.erl"},{line,60}]},{emqttd_protocol,authenticate,2,[{file,"src/emqttd_protocol.erl"},{line,491}]},{emqttd_protocol,process,2,[{file,"src/emqttd_protocol.erl"},{line,182}]},{emqttd_client,received,2,[{file,"src/emqttd_client.erl"},{line,311}]},{gen_server2,handle_msg,2,[{file,"src/gen_server2.erl"},{line,1046}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
16:19:27.450 [info] Client(MQTT_FX_Client@172.22.0.1:42696): SEND CONNACK(Q0, R0, D0, AckFlags=0, RetainCode=4)
16:19:27.451 [info] Client(MQTT_FX_Client@172.22.0.1:42696): Shutdown for auth_failure
```

This is the redis db key content:

```
127.0.0.1:6379> HGETALL mqtt_user:user0
1) "password"
2) "pass0"
127.0.0.1:6379> HGET mqtt_user:user0 password
"pass0"
```

I leave the default acl file in emq.conf:
(...)
mqtt.acl_file = etc/acl.conf
(...)
The same configuration is correctly running with Emqtt 2.0.7 release.

**Emqtt startup console logs**

> mqtt.listener.tcp.max_clients=1000000
> node.max_ets_tables=2097152
> node.process_limit=2097152
> node.name=024cc5e46f5d@172.22.0.3
> mqtt.listener.http.max_clients=250000
> mqtt.listener.ssl.max_clients=500000
> mqtt.listener.tcp.acceptors=64
> node.max_ports=1048576
> mqtt.listener.http.acceptors=16
> mqtt.listener.ssl.acceptors=32
> log.console=console
> EMQ_LOADED_PLUGINS="emq_auth_redis,emq_recon,emq_dashboard,emq_mod_presence,emq_mod_retainer,emq_mod_subscription,emq_stomp"
> Node '024cc5e46f5d@172.22.0.3' not responding to pings.
> Exec: /opt/emqttd/erts-8.1/bin/erlexec -noshell -noinput +Bd -boot /opt/emqttd/releases/2.1.2/emqttd -mode embedded -boot_var ERTS_LIB_DIR /opt/emqttd/erts-8.1/../lib -mnesia dir "/opt/emqttd/data/mnesia/024cc5e46f5d@172.22.0.3" -config /opt/emqttd/data/configs/app.2017.05.18.16.17.09.config -args_file /opt/emqttd/data/configs/vm.2017.05.18.16.17.09.args -vm_args /opt/emqttd/data/configs/vm.2017.05.18.16.17.09.args -- foreground
> Root: /opt/emqttd
> ['2017-05-18T16:17:10Z']:waiting emqttd
> Node '024cc5e46f5d@172.22.0.3' not responding to pings.
> 16:17:11.128 [info] Application lager started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.128 [info] Application gen_logger started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.128 [info] Application esockd started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.128 [info] Application gproc started on node '024cc5e46f5d@172.22.0.3'
> starting emqttd on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.147 [info] Application mnesia started on node '024cc5e46f5d@172.22.0.3'
> emqttd ctl is starting...[ok]
> emqttd hook is starting...[ok]
> emqttd router is starting...[ok]
> emqttd pubsub is starting...[ok]
> emqttd stats is starting...[ok]
> emqttd metrics is starting...[ok]
> emqttd pooler is starting...[ok]
> emqttd trace is starting...[ok]
> emqttd client manager is starting...[ok]
> emqttd session manager is starting...[ok]
> emqttd session supervisor is starting...[ok]
> emqttd wsclient supervisor is starting...[ok]
> emqttd broker is starting...[ok]
> emqttd alarm is starting...[ok]
> emqttd mod supervisor is starting...[ok]
> emqttd bridge supervisor is starting...[ok]
> emqttd access control is starting...[ok]
> emqttd system monitor is starting...[ok]
> 16:17:11.187 [error] Cannot find plugins: [emq_mod_presence,emq_mod_retainer,emq_mod_subscription]
> 16:17:11.187 [info] Application ecpool started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.188 [info] Application eredis started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.192 [info] started Apps: [ecpool,eredis,emq_auth_redis]
> 16:17:11.192 [info] load plugin emq_auth_redis successfully
> 16:17:11.192 [info] Application emq_auth_redis started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.192 [info] Application recon started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.192 [info] started Apps: [recon,emq_recon]
> 16:17:11.192 [info] load plugin emq_recon successfully
> 16:17:11.192 [info] Application emq_recon started on node '024cc5e46f5d@172.22.0.3'
> dashboard:http listen on 0.0.0.0:18083 with 2 acceptors.
> 16:17:11.200 [info] started Apps: [emq_dashboard]
> 16:17:11.200 [info] load plugin emq_dashboard successfully
> 16:17:11.200 [info] Application emq_dashboard started on node '024cc5e46f5d@172.22.0.3'
> stomp listen on 0.0.0.0:61613 with 4 acceptors.
> 16:17:11.201 [info] started Apps: [emq_stomp]
> 16:17:11.201 [info] load plugin emq_stomp successfully
> 16:17:11.201 [info] Application emq_stomp started on node '024cc5e46f5d@172.22.0.3'
> mqtt:tcp listen on 0.0.0.0:1883 with 64 acceptors.
> mqtt:ssl listen on 0.0.0.0:8883 with 32 acceptors.
> mqtt:ws listen on 0.0.0.0:8083 with 16 acceptors.
> mqtt:wss listen on 0.0.0.0:8084 with 32 acceptors.
> emqttd 2.1.2 is running now
> 16:17:11.207 [info] Application emqttd started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.207 [info] Application cbor started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.207 [info] Application eldap started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.207 [info] Application poolboy started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.207 [info] Application bson started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.207 [info] Application mongodb started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.208 [info] Application mysql started on node '024cc5e46f5d@172.22.0.3'
> 16:17:11.208 [info] Application epgsql started on node '024cc5e46f5d@172.22.0.3'
> ['2017-05-18T16:17:11Z']:waiting emqttd
> ['2017-05-18T16:17:12Z']:emqttd start

**etc/emq.conf**

> ##===================================================================
> ## EMQ Configuration R2.1
> ##===================================================================
> 
> ##--------------------------------------------------------------------
> ## Node Args
> ##--------------------------------------------------------------------
> 
> ## Node name
> node.name = 024cc5e46f5d@172.22.0.3
> 
> ## Cookie for distributed node
> node.cookie = emq_dist_cookie
> 
> ## SMP support: enable, auto, disable
> node.smp = auto
> 
> ## vm.args: -heart
> ## Heartbeat monitoring of an Erlang runtime system
> ## Value should be 'on' or comment the line
> ## node.heartbeat = on
> 
> ## Enable kernel poll
> node.kernel_poll = on
> 
> ## async thread pool
> node.async_threads = 32
> 
> ## Erlang Process Limit
> node.process_limit = 2097152
> 
> ## Sets the maximum number of simultaneously existing ports for this system
> node.max_ports = 1048576
> 
> ## Set the distribution buffer busy limit (dist_buf_busy_limit)
> node.dist_buffer_size = 32MB
> 
> ## Max ETS Tables.
> ## Note that mnesia and SSL will create temporary ets tables.
> node.max_ets_tables = 2097152
> 
> ## Tweak GC to run more often
> node.fullsweep_after = 1000
> 
> ## Crash dump
> node.crash_dump = log/crash.dump
> 
> ## Distributed node ticktime
> node.dist_net_ticktime = 60
> 
> ## Distributed node port range
> ## node.dist_listen_min = 6369
> ## node.dist_listen_max = 6369
> 
> ##--------------------------------------------------------------------
> ## Log
> ##--------------------------------------------------------------------
> 
> ## Set the log dir
> log.dir = log
> 
> ## Console log. Enum: off, file, console, both
> log.console = console
> 
> ## Syslog. Enum: on, off
> log.syslog = on
> 
> ##  syslog level. Enum: debug, info, notice, warning, error, critical, alert, emergency
> log.syslog.level = error
> 
> ## Console log level. Enum: debug, info, notice, warning, error, critical, alert, emergency
> log.console.level = info
> 
> ## Console log file
> ## log.console.file = log/console.log
> 
> ## Error log file
> log.error.file = log/error.log
> 
> ## Enable the crash log. Enum: on, off
> log.crash = on
> 
> log.crash.file = log/crash.log
> 
> ##--------------------------------------------------------------------
> ## Allow Anonymous and Default ACL
> ##--------------------------------------------------------------------
> 
> ## Allow Anonymous authentication
> mqtt.allow_anonymous = false
> 
> ## Default ACL File
> mqtt.acl_file = etc/acl.conf
> 
> ## Cache ACL for PUBLISH
> mqtt.cache_acl = true
> 
> ##--------------------------------------------------------------------
> ## MQTT Protocol
> ##--------------------------------------------------------------------
> 
> ## Max ClientId Length Allowed.
> mqtt.max_clientid_len = 1024
> 
> ## Max Packet Size Allowed, 64K by default.
> mqtt.max_packet_size = 64KB
> 
> ##--------------------------------------------------------------------
> ## MQTT Connection
> ##--------------------------------------------------------------------
> 
> ## Force GC: integer. Value 0 disabled the Force GC.
> mqtt.conn.force_gc_count = 100
> 
> ##--------------------------------------------------------------------
> ## MQTT Client
> ##--------------------------------------------------------------------
> 
> ## Client Idle Timeout (Second)
> mqtt.client.idle_timeout = 30s
> 
> ## Enable client Stats: on | off
> mqtt.client.enable_stats = off
> 
> ##--------------------------------------------------------------------
> ## MQTT Session
> ##--------------------------------------------------------------------
> 
> ## Upgrade QoS?
> mqtt.session.upgrade_qos = off
> 
> ## Max Size of the Inflight Window for QoS1 and QoS2 messages
> ## 0 means no limit
> mqtt.session.max_inflight = 32
> 
> ## Retry Interval for redelivering QoS1/2 messages.
> mqtt.session.retry_interval = 20s
> 
> ## Client -> Broker: Max Packets Awaiting PUBREL, 0 means no limit
> mqtt.session.max_awaiting_rel = 100
> 
> ## Awaiting PUBREL Timeout
> mqtt.session.await_rel_timeout = 20s
> 
> ## Enable Statistics: on | off
> mqtt.session.enable_stats = off
> 
> ## Expired after 1 day:
> ## w - week
> ## d - day
> ## h - hour
> ## m - minute
> ## s - second
> mqtt.session.expiry_interval = 2h
> 
> ##--------------------------------------------------------------------
> ## MQTT Queue
> ##--------------------------------------------------------------------
> 
> ## Type: simple | priority
> mqtt.queue.type = simple
> 
> ## Topic Priority: 0~255, Default is 0
> ## mqtt.queue.priority = topic/1=10,topic/2=8
> 
> ## Max queue length. Enqueued messages when persistent client disconnected,
> ## or inflight window is full.
> mqtt.queue.max_length = infinity
> 
> ## Low-water mark of queued messages
> mqtt.queue.low_watermark = 20%
> 
> ## High-water mark of queued messages
> mqtt.queue.high_watermark = 60%
> 
> ## Queue Qos0 messages?
> mqtt.queue.qos0 = true
> 
> ##--------------------------------------------------------------------
> ## MQTT Broker and PubSub
> ##--------------------------------------------------------------------
> 
> ## System Interval of publishing broker $SYS Messages
> mqtt.broker.sys_interval = 60
> 
> ## PubSub Pool Size. Default should be scheduler numbers.
> mqtt.pubsub.pool_size = 8
> 
> mqtt.pubsub.by_clientid = true
> 
> ## Subscribe Asynchronously
> mqtt.pubsub.async = true
> 
> ##--------------------------------------------------------------------
> ## MQTT Bridge
> ##--------------------------------------------------------------------
> 
> ## Bridge Queue Size
> mqtt.bridge.max_queue_len = 10000
> 
> ## Ping Interval of bridge node. Unit: Second
> mqtt.bridge.ping_down_interval = 1
> 
> ##-------------------------------------------------------------------
> ## MQTT Plugins
> ##-------------------------------------------------------------------
> 
> ## Dir of plugins' config
> mqtt.plugins.etc_dir =etc/plugins/
> 
> ## File to store loaded plugin names.
> mqtt.plugins.loaded_file = data/loaded_plugins
> 
> ##--------------------------------------------------------------------
> ## MQTT Listeners
> ##--------------------------------------------------------------------
> 
> ## TCP Listener: 1883, 127.0.0.1:1883, ::1:1883
> mqtt.listener.tcp = 1883
> 
> ## Size of acceptor pool
> mqtt.listener.tcp.acceptors = 64
> 
> ## Maximum number of concurrent clients
> mqtt.listener.tcp.max_clients = 1000000
> 
> ## Rate Limit. Format is 'burst,rate', Unit is KB/Sec
> ## mqtt.listener.tcp.rate_limit = 100,10
> 
> ## TCP Socket Options
> mqtt.listener.tcp.backlog = 1024
> ## mqtt.listener.tcp.recbuf = 4096
> ## mqtt.listener.tcp.sndbuf = 4096
> ## mqtt.listener.tcp.buffer = 4096
> ## mqtt.listener.tcp.nodelay = true
> 
> ## SSL Listener: 8883, 127.0.0.1:8883, ::1:8883
> mqtt.listener.ssl = 8883
> 
> ## Size of acceptor pool
> mqtt.listener.ssl.acceptors = 32
> 
> ## Maximum number of concurrent clients
> mqtt.listener.ssl.max_clients = 500000
> 
> ## Rate Limit. Format is 'burst,rate', Unit is KB/Sec
> ## mqtt.listener.ssl.rate_limit = 100,10
> 
> ## Configuring SSL Options. See http://erlang.org/doc/man/ssl.html
> ### TLS only for POODLE attack
> mqtt.listener.ssl.tls_versions = tlsv1.2,tlsv1.1,tlsv1
> mqtt.listener.ssl.handshake_timeout = 15s
> mqtt.listener.ssl.keyfile = etc/certs/key.pem
> mqtt.listener.ssl.certfile = etc/certs/cert.pem
> #mqtt.listener.ssl.cacertfile = etc/certs/cacert.pem
> #mqtt.listener.ssl.verify = verify_peer
> #mqtt.listener.ssl.fail_if_no_peer_cert = true
> 
> ## HTTP and WebSocket Listener
> mqtt.listener.http = 8083
> mqtt.listener.http.acceptors = 16
> mqtt.listener.http.max_clients = 250000
> 
> ## HTTP(SSL) Listener
> mqtt.listener.https = 8084
> mqtt.listener.https.acceptors = 32
> mqtt.listener.https.max_clients = 1000000
> mqtt.listener.https.handshake_timeout = 15
> mqtt.listener.https.keyfile = etc/certs/key.pem
> mqtt.listener.https.certfile = etc/certs/cert.pem
> # mqtt.listener.https.cacertfile = etc/certs/cacert.pem
> 
> ## mqtt.listener.https.verify = verify_peer
> ## mqtt.listener.https.fail_if_no_peer_cert = true
> 
> ##-------------------------------------------------------------------
> ## System Monitor
> ##-------------------------------------------------------------------
> 
> ## Long GC, don't monitor in production mode for:
> ## https://github.com/erlang/otp/blob/feb45017da36be78d4c5784d758ede619fa7bfd3/erts/emulator/beam/erl_gc.c#L421
> sysmon.long_gc = false
> 
> ## Long Schedule(ms)
> sysmon.long_schedule = 240
> 
> ## 8M words. 32MB on 32-bit VM, 64MB on 64-bit VM.
> sysmon.large_heap = 8MB
> 
> ## Busy Port
> sysmon.busy_port = false
> 
> ## Busy Dist Port
> sysmon.busy_dist_port = true

**etc/acl.conf**

> %%--------------------------------------------------------------------
> %%
> %% [ACL](https://github.com/emqtt/emqttd/wiki/ACL)
> %%
> %% -type who() :: all | binary() |
> %%                {ipaddr, esockd_access:cidr()} |
> %%                {client, binary()} |
> %%                {user, binary()}.
> %%
> %% -type access() :: subscribe | publish | pubsub.
> %%
> %% -type topic() :: binary().
> %%
> %% -type rule() :: {allow, all} |
> %%                 {allow, who(), access(), list(topic())} |
> %%                 {deny, all} |
> %%                 {deny, who(), access(), list(topic())}.
> %%
> %%--------------------------------------------------------------------
> 
> {allow, {user, "dashboard"}, subscribe, ["$SYS/#"]}.
> 
> {allow, {ipaddr, "127.0.0.1"}, pubsub, ["$SYS/#", "#"]}.
> 
> {deny, all, subscribe, ["$SYS/#", {eq, "#"}]}.
> 
> {deny, all}.

**etc/plugins/emq_auth_redis.conf**

> ##--------------------------------------------------------------------
> ## Redis Auth/ACL Plugin
> ##--------------------------------------------------------------------
> 
> ## Redis Server
> auth.redis.server = redis:6379
> 
> ## Redis Pool Size
> auth.redis.pool = 8
> 
> ## Redis Database
> auth.redis.database = 0
> 
> ## Redis Password
> ## auth.redis.password =
> 
> ## Variables: %u = username, %c = clientid
> 
> ## Authentication Query Command
> auth.redis.auth_cmd = HGET mqtt_user:%u password
> 
> ## Password hash: plain, md5, sha, sha256, pbkdf2
> auth.redis.password_hash = plain
> 
> ## Superuser Query Command
> auth.redis.super_cmd = HGET mqtt_user:%u is_superuser
> 
> ## ACL Query Command
> auth.redis.acl_cmd = HGETALL mqtt_acl:%u
> 
> ## ACL nomatch
> auth.redis.acl_nomatch = deny

**Comment by huangdan** [comment]
hi @totojack  The Authentication Query Command:
```
Authentication Query Command
auth.redis.auth_cmd = HMGET mqtt_user:%u password
```
