### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by encojosh** [emqtt/emq-auth-redis#43]
Previous versions of this plugin supported storing subscriptions in the redis plugin.  The help documents for this mentions that it was moved to emqtt_backend_redis, but I can't find any reference to that plugin.  I used the following command format, but it did not work.

HSET mqtt_sub:<username> topic1 0
HSET mqtt_sub:<username> topic2 1
HSET mqtt_sub:<username> topic3 2

**Comment by pewh** [comment]
+1

**Comment by encojosh** [comment]
Any updates on this?

**Comment by emqplus** [comment]
@encojosh This feature has been moved to enterprise edition.
